name: oidctest
on:
    workflow_dispatch:
permissions:
    contents: read
    id-token: write
jobs:
    aws_authentication:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v6 
              with:
                role-to-assume: ${{secrets.AWS_ROLE_ARN}}
                aws-region: US-EAST-1
                role-session-name: githublink
            - name: Test OIDC authentication
              run: |
                  aws sts get-caller-identity
